# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 01:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170901_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. Up to 12 digits allowed.", regex='^\\+?1?\\d{8,12}$')]),
        ),
    ]
